// docs/18: the player guide as it ships. Generated from the text between the two rules in docs/18-player-guide.md;
// what differs from it is listed in docs/11-status.md ("Player guide"). An admin's own text, once saved in
// Admin -> Branding, replaces this.

import { SITE_HOST } from "@/shared/site";

export const DEFAULT_GUIDE = [
  "## Getting in",
  "",
  `1. Go to ${SITE_HOST} and sign in with Discord.`,
  "2. Download DeepslateWorks.exe and run it once.",
  "3. After that, just press **Play** on the site or open Deepslate Works from your desktop. It keeps itself up to date.",
  "",
  "The first time you join you'll be in a small room. Click the link in chat or right-click the book in your hand, sign in with Discord, and you're through. You never need to type a username or ask to be whitelisted.",
  "",
  "If pressing T says chat isn't allowed, your Microsoft account has chat switched off. You can still get in with the book or the code. To turn chat on: account.xbox.com → Privacy & online safety → Xbox privacy → allow communicating outside of Xbox with voice and text (on a family account, the organiser changes it at family.microsoft.com), then restart Minecraft.",
  "",
  "## Where things are on the site",
  "",
  "- **Home**: is the server on, who's playing, the live map.",
  "- **Map**: full-screen live map with everyone's position. Press M in the game for the same map on your screen.",
  "- **Players**: who's in the group and when they last played.",
  "- **Stats**: play time, deaths, who plays most, busiest hours.",
  "- **Events**: joins, deaths, server restarts.",
  "- **Me**: your account, your last install, and quick actions once they're switched on.",
  "",
  "## The basics that are different from vanilla",
  "",
  "Every mod has a card in the [Mods guide](/mods) with how to start and its keys. The few you'll use in your first minutes:",
  "",
  "- **JEI**: press R on any item to see how it's made. [More](/mods#jei) <!-- mod: jei -->",
  "- **Jade**: look at a block or mob and it says what it is. [More](/mods#jade) <!-- mod: jade -->",
  "- **Voice chat**: hold the talk key to speak to people near you. [Keys and setup](/mods#simple-voice-chat) <!-- mod: simple-voice-chat -->",
  "- **Maps**: a minimap in the corner and a big map on M. [More](/mods#xaeros-minimap) <!-- mod: xaeros-minimap -->",
  "- **Tab**: who's on, everyone's ping and the server's TPS. [More](/mods#bettertabinfo) <!-- mod: bettertabinfo -->",
  "- **Corpse**: When you die, your things stay in your body where you fell. It never disappears. For 30 minutes only you can open it; after that your friends can too. [More](/mods#corpse) <!-- mod: corpse -->",
  "- **Backpacks**: you start with one in your inventory. A magnet upgrade comes later. [More](/mods#sophisticated-backpacks) <!-- mod: sophisticated-backpacks -->",
  "- **Waystones**: teleport between the ones you've found. [More](/mods#waystones) <!-- mod: waystones -->",
  "- **VeinMiner**: a whole vein of ore in one go. [More](/mods#veinminer) <!-- mod: veinminer -->",
  "- **FallingTree**: break the bottom log and the whole tree comes down. [More](/mods#fallingtree) <!-- mod: fallingtree -->",
  "- **Render distance**: yours (Options → Video Settings → Render Distance) can be lower than the server's but not higher: past the server's distance there is nothing to show. On a slower PC turn it down; 8 is plenty.",
  "",
  "## Playing with friends <!-- mod: open-parties-and-claims -->",
  "",
  "1. Press **'** (apostrophe, next to Enter) to open the parties and claims screen.",
  "2. Create a party, then invite your friends by their Minecraft name.",
  "3. They press ' too and accept. From then on you see each other on the minimap and the world map (M), however far apart you are. Allied parties show up as well.",
  "",
  "Optional: claim your base. Open the world map (M), right-click a chunk and choose **Claim**. You get up to 200 chunks. In your claims only you and your party can break, build and open chests; your Create machines and pipes keep working inside your own claim. Claims stay as long as you've played in the last 90 days. The spawn area belongs to the server and can't be claimed.",
  "",
  "Quarries don't dig in claimed chunks (yours included): leave the quarry's area unclaimed and claim the rest of your base. <!-- mod: additional-enchanted-miner -->",
  "",
  "## Your first hour",
  "",
  "1. Punch a tree, make a crafting table, make a wooden then stone pickaxe as usual.",
  "2. Open your backpack: you start with one, with tools, bread, torches and a bed. <!-- mod: sophisticated-backpacks -->",
  "3. Find a waystone or build one so you can always get home. <!-- mod: waystones -->",
  "4. Pick a spot for your base away from spawn and other people; use a waypoint (B) to mark it.",
  "",
  "Spawn is protected: you can't break or build there.",
  "",
  "## Power and machines <!-- mod: create -->",
  "",
  "Create is the factory mod: everything runs on rotation, from water wheels to steam engines and trains. How to start, and the Ponder animations: [Create in the Mods guide](/mods#create).",
  "",
  "## Electricity <!-- mod: createaddition -->",
  "",
  "Create: Crafts & Additions turns rotation into electricity for machines like the quarry. [How](/mods#createaddition)",
  "",
  "## The quarry <!-- mod: additional-enchanted-miner -->",
  "",
  "How to set one up: [the quarry in the Mods guide](/mods#additional-enchanted-miner).",
  "",
  "Please: quarries only well away from spawn and from other people's bases. They leave big holes. Fill in or fence off anything near a path.",
  "",
  "## Pipes <!-- mod: pipez -->",
  "",
  "One pipe each for items, fluids and power. [How to connect them](/mods#pipez)",
  "",
  "## Guns <!-- mod: tacz-1.21.1 -->",
  "",
  "Crafting, ammo and the keys: [Guns in the Mods guide](/mods#tacz-1.21.1). There's no PvP on this server, so they're for mobs.",
  "",
  "## Building <!-- mod: create-deco, copycats, macaws-roofs, macaws-windows, macaws-doors, handcrafted -->",
  "",
  "More blocks for your base: Create Deco, Copycats, Macaw's roofs, windows and doors, and Handcrafted furniture. Each has a card in the [Mods guide](/mods).",
  "",
  "## Making it look nicer",
  "",
  "In the Deepslate Works app (the window that opens when you press Play), the **Extras** tab has optional visual extras, only for your PC. Nobody votes on them and nobody else needs them: you can play together either way. What each one does: [Your extras in the Mods guide](/mods#iris).",
  "",
  "Switch the ones you want on, pick **Shaders** (None, Light or Full; only with Iris on) and press **Apply**. Each one shows how much it costs in FPS; on an older laptop, try the Low ones first, and Light shaders before Full. If the game is running, the app asks to restart it. Switch them off the same way: everything goes back as it was.",
  "",
  "## Home, spawn and getting unstuck <!-- feature: actions -->",
  "",
  "On the **Me** page:",
  "- **Take me to spawn**: teleports you to spawn.",
  "- **Set my home** / **Take me home**: one saved spot.",
  "- **Where am I**: your coordinates and dimension.",
  "- **Unstick me**: if you're wedged somewhere, this kills you so you respawn. Your stuff stays in your corpse.",
  "",
  "Each of these has a cooldown so nobody spams them.",
  "",
  "## Rules",
  "",
  "Short version, the full version is on the Rules page:",
  "- Don't grief. Don't take from chests that aren't yours.",
  "- Quarries and big machines away from spawn and other bases.",
  "- If you leave the Discord server you lose access to the game.",
  "- Be nice on voice chat.",
  "",
  "## Something's broken?",
  "",
  "- Game won't start after an update: press Play on the site again. If it still fails, the site will have your install log and Alex will look.",
  "- \"Mod mismatch\" when joining: same thing, press Play on the site so your mods match the server.",
  "- Server shows \"asleep\": just join, it wakes up in about 30 seconds.",
  "- Anything else: ask in the Discord.",
].join("\n");
