// docs/18: the player guide as it ships. Generated from the text between the two rules in docs/18-player-guide.md;
// what differs from it is listed in docs/11-status.md ("Player guide"). An admin's own text, once saved in
// Admin -> Branding, replaces this.

export const DEFAULT_GUIDE = [
  "## Getting in",
  "",
  "1. Go to deepslate.dsw.test and sign in with Discord.",
  "2. Download, double-click Setup.bat once.",
  "3. After that, just press **Play** on the site or open Deepslate Works from your desktop. It keeps itself up to date.",
  "",
  "The first time you join you'll be in a small room. Click the link in chat or right-click the book in your hand, sign in with Discord, and you're through. You never need to type a username or ask to be whitelisted.",
  "",
  "If pressing T says chat isn't allowed, your Microsoft account has chat switched off. You can still get in with the book or the code. To turn chat on: account.xbox.com → Privacy & online safety → Xbox privacy → allow communicating outside of Xbox with voice and text (on a family account, the organiser changes it at family.microsoft.com), then restart Minecraft.",
  "",
  "## Where things are on the site",
  "",
  "- **Home**: is the server on, who's playing, the live map.",
  "- **Map**: full-screen live map with everyone's position. Press M in the game for the same map on your screen.",
  "- **Players**: who's in the group and when they last played.",
  "- **Stats**: play time, deaths, who plays most, busiest hours.",
  "- **Events**: joins, deaths, server restarts.",
  "- **Me**: your account, your last install, and quick actions once they're switched on.",
  "",
  "## The basics that are different from vanilla",
  "",
  "- **JEI**: press R on any item to see how it's made, U to see what it makes. Type in the search box bottom-right to find anything.",
  "- **Jade**: look at a block or mob and it tells you what it is at the top of the screen.",
  "- **Voice chat**: hold V to talk to people near you. Press V once to open the settings (mute, volume, push-to-talk key).",
  "- **Minimap**: corner of the screen. M opens the big map. Press B to drop a waypoint where you stand.",
  "- **Tab**: press Tab: who's on, everyone's ping, and the server's TPS (20 is perfect). <!-- mod: bettertabinfo -->",
  "- **Corpse**: when you die, your stuff stays in a body where you fell. Only you can loot it for the first while. It shows on the map.",
  "- **Backpacks**: craft one early. Upgrade it later with a magnet so it picks things up for you. <!-- mod: sophisticated-backpacks -->",
  "- **Waystones**: find or build one, click it, and you can teleport between any you've discovered. <!-- mod: waystones -->",
  "- **VeinMiner**: hold the grave key (` under Esc) while breaking ore or a log and the whole vein or tree comes out. Costs hunger, so bring food. <!-- mod: veinminer -->",
  "- **FallingTree**: break the bottom log and the tree falls, with an axe or by hand. Sneak to take one log. <!-- mod: fallingtree -->",
  "- **Render distance**: yours (Options → Video Settings → Render Distance) can be lower than the server's but not higher: past the server's distance there is nothing to show. On a slower PC turn it down; 8 is plenty.",
  "",
  "## Playing with friends <!-- mod: open-parties-and-claims -->",
  "",
  "1. Press **'** (apostrophe, next to Enter) to open the parties and claims screen.",
  "2. Create a party, then invite your friends by their Minecraft name.",
  "3. They press ' too and accept. From then on you see each other on the minimap and the world map (M), however far apart you are. Allied parties show up as well.",
  "",
  "Optional: claim your base. Open the world map (M), right-click a chunk and choose **Claim**. You get up to 200 chunks. In your claims only you and your party can break, build and open chests; your Create machines and pipes keep working inside your own claim. Claims stay as long as you've played in the last 90 days. The spawn area belongs to the server and can't be claimed.",
  "",
  "Quarries don't dig in claimed chunks (yours included): leave the quarry's area unclaimed and claim the rest of your base. <!-- mod: additional-enchanted-miner -->",
  "",
  "## Your first hour",
  "",
  "1. Punch a tree, make a crafting table, make a wooden then stone pickaxe as usual.",
  "2. Craft a backpack as soon as you have leather or wool. <!-- mod: sophisticated-backpacks -->",
  "3. Find a waystone or build one so you can always get home. <!-- mod: waystones -->",
  "4. Pick a spot for your base away from spawn and other people; use a waypoint (B) to mark it.",
  "",
  "## Power and machines <!-- mod: create -->",
  "",
  "Create is the factory mod. Everything runs on rotation from **water wheels** and **windmills** to start with. Rough order:",
  "",
  "1. Andesite alloy (andesite + iron nugget) → **shafts**, **cogwheels**, **mechanical press**.",
  "2. Water wheel next to flowing water → shaft → whatever you want to turn.",
  "3. Mechanical press + belt = automatic plates. Millstone = flour, dyes, gravel to sand.",
  "4. Later: steam engines for serious power, trains if you get ambitious.",
  "",
  "Press R on any Create block and JEI shows the recipe; most Create blocks also have a little animated guide (Ponder) if you hold W over them in JEI.",
  "",
  "## Electricity <!-- mod: createaddition -->",
  "",
  "Create: Crafts & Additions turns rotation into electricity. **Alternator** on a spinning shaft → **wires** → machines that want power (the quarry, for one). Batteries store it.",
  "",
  "## The quarry <!-- mod: additional-enchanted-miner -->",
  "",
  "Mark out an area with **markers** (place them at the corners, right-click to link), put down the **quarry** block, give it power, and it digs everything inside the area down to bedrock into a chest or pipe next to it.",
  "",
  "Please: quarries only well away from spawn and from other people's bases. They leave big holes. Fill in or fence off anything near a path.",
  "",
  "## Pipes <!-- mod: pipez -->",
  "",
  "Pipez gives one pipe each for items, fluids and power. Place it against a chest or machine, then use the **wrench** on the end to set pull or push. That's all you need to connect a quarry to a chest or a generator to a machine.",
  "",
  "## Guns <!-- mod: tacz-1.21.1 -->",
  "",
  "Guns are crafted on the **gun workbench** (needs Create parts). Press R to reload, hold right-click to aim, Z to switch fire mode. Ammo is crafted at the same bench. There's no PvP on this server, so they're for mobs.",
  "",
  "## Building <!-- mod: create-deco, copycats, macaws-roofs, macaws-windows, macaws-doors, handcrafted -->",
  "",
  "More blocks for your base: Create Deco's metal and lamps, copycat blocks that copy any texture, Macaw's roofs, windows and doors, and Handcrafted furniture. Look them up in JEI (press R on a block, U for what it's used in).",
  "",
  "## Making it look nicer",
  "",
  "In the Deepslate Works app (the window that opens when you press Play), the **Extras** tab has optional visual extras, only for your PC: shaders, better animations, 3D skin layers, falling leaves, rain you can see, echoes in caves and Fresh Animations for mobs. Nobody votes on them and nobody else needs them: you can play together either way.",
  "",
  "Switch the ones you want on, pick **Shaders** (None, Light or Full; only with Iris on) and press **Apply**. Each one shows how much it costs in FPS; on an older laptop, try the Low ones first, and Light shaders before Full. If the game is running, the app asks to restart it. Switch them off the same way: everything goes back as it was.",
  "",
  "## Home, spawn and getting unstuck <!-- feature: actions -->",
  "",
  "On the **Me** page:",
  "- **Take me to spawn**: teleports you to spawn.",
  "- **Set my home** / **Take me home**: one saved spot.",
  "- **Where am I**: your coordinates and dimension.",
  "- **Unstick me**: if you're wedged somewhere, this kills you so you respawn. Your stuff stays in your corpse.",
  "",
  "Each of these has a cooldown so nobody spams them.",
  "",
  "## Rules",
  "",
  "Short version, the full version is on the Rules page:",
  "- Don't grief. Don't take from chests that aren't yours.",
  "- Quarries and big machines away from spawn and other bases.",
  "- If you leave the Discord server you lose access to the game.",
  "- Be nice on voice chat.",
  "",
  "## Something's broken?",
  "",
  "- Game won't start after an update: press Play on the site again. If it still fails, the site will have your install log and Alex will look.",
  "- \"Mod mismatch\" when joining: same thing, press Play on the site so your mods match the server.",
  "- Server shows \"asleep\": just join, it wakes up in about 30 seconds.",
  "- Anything else: ask in the Discord.",
].join("\n");
